github:
- changed-files:
  - any-glob-to-any-file: '.github/**/*'

taxonomies:
- changed-files:
  - any-glob-to-any-file: 'app/src/androidTest/java/openfoodfacts/github/scrachx/openfood/repositories/TaxonomiesRepositoryTest.kt'
  - any-glob-to-any-file: 'app/src/main/java/openfoodfacts/github/scrachx/openfood/repositories/TaxonomiesManager.kt'
  - any-glob-to-any-file: 'app/src/main/java/openfoodfacts/github/scrachx/openfood/repositories/Taxonomy.kt'
  - any-glob-to-any-file: 'app/src/main/java/openfoodfacts/github/scrachx/openfood/repositories/TaxonomiesRepository.kt'

lists:
- changed-files:
  - any-glob-to-any-file: 'app/src/main/res/menu/menu_your_listed_products.xml'
  - any-glob-to-any-file: 'app/src/main/res/layout/your_listed_products_item.xml'
  - any-glob-to-any-file: 'app/src/main/res/layout/activity_your_listed_products.xml'
  - any-glob-to-any-file: 'app/src/main/res/layout-v21/activity_your_listed_products.xml'
  - any-glob-to-any-file: 'app/src/main/java/openfoodfacts/github/scrachx/openfood/models/entities/ListedProduct.java'
  - any-glob-to-any-file: 'app/src/main/java/openfoodfacts/github/scrachx/openfood/features/productlist/ProductListAdapter.kt'
  - any-glob-to-any-file: 'app/src/main/java/openfoodfacts/github/scrachx/openfood/features/productlist/ProductListActivity.kt'
  - any-glob-to-any-file: 'app/src/main/java/openfoodfacts/github/scrachx/openfood/features/productlists/ProductListsAdapter.kt'
  - any-glob-to-any-file: 'app/src/main/java/openfoodfacts/github/scrachx/openfood/features/productlists/ProductListsActivity.kt'

allergen alert:
- changed-files:
  - any-glob-to-any-file: 'app/src/test/java/openfoodfacts/github/scrachx/openfood/models/entities/allergen/AllergenResponseTestData.kt'
  - any-glob-to-any-file: 'app/src/test/java/openfoodfacts/github/scrachx/openfood/models/entities/allergen/AllergensWrapperTest.kt'
  - any-glob-to-any-file: 'app/src/test/java/openfoodfacts/github/scrachx/openfood/models/entities/allergen/AllergenTest.kt'
  - any-glob-to-any-file: 'app/src/test/java/openfoodfacts/github/scrachx/openfood/models/entities/allergen/AllergenResponseTest.kt'
  - any-glob-to-any-file: 'app/src/main/java/openfoodfacts/github/scrachx/openfood/features/allergensalert/AllergensAlertViewModel.kt'
  - any-glob-to-any-file: 'app/src/main/java/openfoodfacts/github/scrachx/openfood/features/allergensalert/AllergensAdapter.kt'
  - any-glob-to-any-file: 'app/src/main/java/openfoodfacts/github/scrachx/openfood/features/allergensalert/AllergensAlertFragment.kt'
  - any-glob-to-any-file: 'app/src/main/java/openfoodfacts/github/scrachx/openfood/repositories/AllergenPreferencesRepository.kt'
  - any-glob-to-any-file: 'app/src/main/java/openfoodfacts/github/scrachx/openfood/models/entities/allergen/AllergenResponse.kt'
  - any-glob-to-any-file: 'app/src/main/java/openfoodfacts/github/scrachx/openfood/models/entities/allergen/AllergenName.java'
  - any-glob-to-any-file: 'app/src/main/java/openfoodfacts/github/scrachx/openfood/models/entities/allergen/AllergensWrapperDeserializer.kt'
  - any-glob-to-any-file: 'app/src/main/java/openfoodfacts/github/scrachx/openfood/models/entities/allergen/AllergensWrapper.kt'
  - any-glob-to-any-file: 'app/src/main/java/openfoodfacts/github/scrachx/openfood/models/entities/allergen/Allergen.java'
  - any-glob-to-any-file: 'app/src/main/java/openfoodfacts/github/scrachx/openfood/models/entities/allergen/AllergenHelper.kt'

questions:
- changed-files:
  - any-glob-to-any-file: 'app/src/main/java/openfoodfacts/github/scrachx/openfood/repositories/RobotoffRepository.kt'

screenshots:
- changed-files:
  - any-glob-to-any-file: 'app/src/androidTestScreenshots/java/openfoodfacts/github/scrachx/openfood/test/ScreenshotParameter.kt'
  - any-glob-to-any-file: 'app/src/androidTestScreenshots/java/openfoodfacts/github/scrachx/openfood/test/ScreenshotActivityTestRule.kt'
  - any-glob-to-any-file: 'app/src/androidTestScreenshots/java/openfoodfacts/github/scrachx/openfood/test/ScreenshotTaker.kt'
  - any-glob-to-any-file: 'app/src/androidTestScreenshots/java/openfoodfacts/github/scrachx/openfood/test/ScreenshotParametersProvider.kt'
  - any-glob-to-any-file: 'app/src/androidTestScreenshots/java/openfoodfacts/github/scrachx/openfood/test/ScreenshotsLocaleProvider.kt'

translations:
- changed-files:
  - any-glob-to-any-file: 'app/src/off/res/values-*'
  - any-glob-to-any-file: 'app/src/obf/res/values-*'
  - any-glob-to-any-file: 'app/src/opf/res/values-*'
  - any-glob-to-any-file: 'app/src/opff/res/values-*'

open beauty facts:
- changed-files:
  - any-glob-to-any-file: 'app/src/obf/res/values-*'

open products facts:
- changed-files:
  - any-glob-to-any-file: 'app/src/opf/res/values-*'

open pet food facts:
- changed-files:
  - any-glob-to-any-file: 'app/src/opff/res/values-*'

changelog:
  - any-glob-to-any-file: 'app/src/main/assets/changelog/*'
